# Generated by Django 4.0.1 on 2022-01-06 02:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bond_name', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bond_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('bond_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=13, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
